title: save
description: Blog created using github issues
url: https://nntrn.github.io
baseurl: /save
repository: nntrn/save
github_username: nntrn
favicon_ico: /assets/favicon.ico
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

page_gen-dirs: false

page_gen:
  - data: "body"
    template: "body"
    index_files: true
    dir: "number"

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  endings: all
  comments: ["<!--", "-->"]
  startings: []
  blanklines: true
  profile: false

exclude:
  - Gemfile
  - Gemfile.lock
  - _issues/
  - scripts
  - .cache
  - save2
