title: save
description: Create blog posts from issues

url: https://nntrn.github.io
baseurl: /save
repository: nntrn/save
github_username: nntrn


favicon_ico: favicon.ico

defaults:
  - scope:
      path: "_issues"
    values:
      layout: default      

collections:
  issues:
    output: true
    permalink: /:name

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compact

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  endings: all
  comments: ["<!--", "-->"]
  startings: []
  blanklines: true
  profile: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  
  
  
  
# # Single letter or emoji to use as favicon
# icon: A

# svg_path_icon: >
#   M4.75 2.37a6.501 6.501 0 0 0 6.5 11.26.75.75 0 0 1 .75 1.298A7.999 7.999 0 0 1 .989
#   4.148 8 8 0 0 1 16 7.75v1.5a2.75 2.75 0 0 1-5.072 1.475 3.999 3.999 0 0 1-6.65-4.19A4
#   4 0 0 1 12 8v1.25a1.25 1.25 0 0 0 2.5 0V7.867a6.5 6.5 0 0 0-9.75-5.496ZM10.5 8a2.5 2.5
#   0 1 0-5 0 2.5 2.5 0 0 0 5 0Z
