name: Test trigger issue

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]

env:
  ARTIFACTS_URL: https://api.github.com/repos/nntrn/save/actions/artifacts

jobs:
  create_content:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.triggering_actor
    steps:
      - uses: actions/checkout@v4
      - name: Environment
        run: >
          env | sort
      - name: Environment
        run: echo -e '```json\n${{ fromJSON(github) }}\n```' >>$GITHUB_STEP_SUMMARY
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
