name: Test trigger issue

on:
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited]

jobs:
  create_content:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.triggering_actor
    steps:
      - uses: actions/checkout@v4
      - name: Environment
        run: >
          env | sort
      - name: Download
        run: |
          LAST_ARCHIVE_URL="$(
            curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$ARTIFACTS_URL" |
              jq -r '.artifacts|sort_by(.created_at)|map(select(.expired|not))|last|.archive_download_url? // ""'
          )"

          if [[ -n $LAST_ARCHIVE_URL ]]; then
            curl -o ghpage.zip -L -H "Authorization: Bearer $GITHUB_TOKEN" "$LAST_ARCHIVE_URL"
            unzip ghpage.zip
            mkdir _site
            tar -xf artifact.tar -C _site
          else
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
